services:
  django:
    command: python manage.py runserver 0.0.0.0:$DJANGO_PORT
    ports:
      - 127.0.0.1:$DJANGO_PORT:$DJANGO_PORT
    env_file:
      - ./secrets/.dev.env

  redis:
    env_file:
      - ./secrets/.dev.env
