# merge with prod compose file

services:
  django:
    env_file:
      - ./git-safe/.preprod.safe.env

  nginx:
    build:
      target: preprod
    env_file:
      - ./git-safe/.preprod.safe.env
    develop:
      watch:
        - path: ./statics
          target: /statics
          action: sync
