services:
  django:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./secrets/.dev.env

  redis:
    env_file:
      - ./secrets/.dev.env
