FROM nginx:1.26.0 as prod

COPY nginx.conf /etc/nginx/
RUN touch /etc/nginx/conf.d/user-media.conf
COPY static.conf /etc/nginx/conf.d/
# template used for environment variables susbstitution
COPY nginx.conf.template /etc/nginx/templates/

RUN mkdir -p /log && touch /log/error.log && touch /log/access.log

# shouldn't need to increase max conenctions supported because linux kernel was updated in 2019 to
# default to 4096 (no longer need 'net.core.somaxconn = 4096')


FROM prod as preprod
# let nginx host media to simulate remote storage from django's perspective
COPY user-media.conf /etc/nginx/conf.d/