# Generated by Django 5.0.3 on 2024-03-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForProxyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('field2', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['field'],
            },
        ),
        migrations.CreateModel(
            name='ParentNonAbstractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyModel',
            fields=[
            ],
            options={
                'ordering': ['-field'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('practice.baseforproxymodel',),
        ),
        migrations.CreateModel(
            name='ExtendedNonAbstractModel',
            fields=[
                ('parent_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='practice.parentnonabstractmodel')),
            ],
            options={
                'ordering': [],
            },
            bases=('practice.parentnonabstractmodel',),
        ),
        migrations.CreateModel(
            name='ConcreteOfAbstractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('field2', models.CharField(max_length=20)),
                ('foreign_key_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='practice.parentnonabstractmodel')),
            ],
            options={
                'db_table': 'practice_concrete_custom_table_name',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('A', 'Choice A'), ('B', 'Choice B'), ('C', 'Choice C'), ('D', 'Choice D')], db_column='custom_field_column_name', db_default='', default='Default Value', help_text='field documentation', max_length=20, verbose_name='Verbose Field Name')),
            ],
            options={
                'verbose_name': 'simple model custom name',
                'db_table': 'practice_simplemodel_custom_table_name',
                'ordering': ['field_name'],
                'permissions': [('extra_permission_code', 'human-readable permission')],
                'abstract': False,
                'managed': True,
                'indexes': [models.Index(fields=['field_name'], name='field_name_idx')],
            },
        ),
    ]
