# Generated by Django 5.0.3 on 2024-03-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnonabstractmodel',
            name='generic_field',
            field=models.CharField(db_default='', max_length=20),
        ),
    ]
