# Generated by Django 5.0.3 on 2024-03-26 20:20

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_parentnonabstractmodel_generic_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteofabstractmodel',
            name='field3',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
