# Generated by Django 5.0.3 on 2024-03-26 20:33

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_concreteofabstractmodel_field3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteofabstractmodel',
            name='field3',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
