# Generated by Django 5.0.3 on 2024-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_concreteofabstractmodel_field3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteofabstractmodel',
            name='field2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
