# Generated by Django 5.0.3 on 2024-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_concreteofabstractmodel_field2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteofabstractmodel',
            name='field',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
