# Generated by Django 5.0.3 on 2024-03-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_alter_concreteofabstractmodel_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteofabstractmodel',
            name='fieldThatWeHideInAdmin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
