# Generated by Django 5.0.3 on 2024-03-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_rename_fieldthatwehideinadmin_concreteofabstractmodel_field_that_we_hide_in_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteofabstractmodel',
            name='self_friends',
            field=models.ManyToManyField(blank=True, null=True, to='practice.concreteofabstractmodel'),
        ),
    ]
