# Generated by Django 5.0.3 on 2024-03-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_concreteofabstractmodel_self_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteofabstractmodel',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
