# Generated by Django 5.0.3 on 2024-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_concreteofabstractmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteofabstractmodel',
            name='self_enemies',
            field=models.ManyToManyField(blank=True, null=True, to='practice.concreteofabstractmodel'),
        ),
    ]
