# Generated by Django 5.0.3 on 2024-04-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_alter_concreteofabstractmodel_self_enemies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplemodel',
            options={'managed': True, 'ordering': ['field_name'], 'permissions': [('custom_permission_code', 'human-readable permission')], 'verbose_name': 'simple model custom name'},
        ),
    ]
