# Generated by Django 5.0.3 on 2024-04-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_alter_simplemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteofabstractmodel',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
