# Generated by Django 5.0.3 on 2024-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0014_alter_concreteofabstractmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteofabstractmodel',
            name='field2',
            field=models.CharField(blank=True, help_text='Field 2 help text', max_length=20, verbose_name='Field 2'),
        ),
    ]
