# Generated by Django 5.0.3 on 2024-04-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0015_alter_concreteofabstractmodel_field2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationAndCustomizationExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=20)),
                ('field2', models.CharField(max_length=20)),
                ('field3', models.CharField(max_length=20)),
            ],
        ),
    ]
