# Generated by Django 5.0.3 on 2024-04-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0016_validationandcustomizationexamplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteofabstractmodel',
            name='slug',
            field=models.SlugField(default='', editable=False, help_text='auto-generated from field and field2 at record creation only', max_length=100),
        ),
    ]
