FROM node:20.17.0-slim AS base
RUN npm install -g pnpm
COPY . /backend
WORKDIR /backend
EXPOSE 8000

# smaller image size 
FROM base AS prod-deps
RUN --mount=type=cache,id=express-deps,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS dev-deps
RUN --mount=type=cache,id=express-deps,target=/pnpm/store pnpm install --frozen-lockfile

FROM prod-deps AS prod
COPY --from=prod-deps /backend/node_modules /backend/node_modules
RUN pnpm build
CMD [ "pnpm", "start" ]

FROM dev-deps AS dev
COPY --from=dev-deps /backend/node_modules /backend/node_modules
CMD [ "pnpm", "devstart" ]
