name: Playwright Tests
on:
  # turn off to avoid constantly running this accidentally
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "learning_js/test-automation-practice/**"
  workflow_dispatch:
    # automatically has last branch/tag and last commit
jobs:
  test:
    env:
      CI: true
      STAGING: 0
    defaults:
      run:
        working-directory: learning_js/test-automation-practice
    timeout-minutes: 5
    runs-on: ubuntu-latest
    # has all playwright browsers and browser deps installed
    container:
      image: mcr.microsoft.com/playwright:v1.42.0
    steps:
      - uses: actions/checkout@v4
        name: Checkout repo
        with:
          repository: ${{ github.repository }} # default
          ref: "" # defaults to SHA that triggered the workflow
          fetch-depth: 1 # default

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        id: cache-pnpm
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('learning_js/test-automation-practice/pnpm-lock.yaml') }}
          # an old cache is still useful if it contains some of the same dependencies
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - if: ${{ steps.cache-pnpm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: echo 'cache miss for node modules' ; pnpm list

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Run Playwright tests on built project
        run: pnpm exec playwright test
        env:
          HOME: /root

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: learning_js/test-automation-practice/playwright-report/
          retention-days: 30
