name: Playwright Tests on LambdaTest
on:
  workflow_dispatch:
    # automatically has last branch/tag and last commit
jobs:
  lambdatest:
    env:
      REMOTE_TEST: true
      CI: true
      STAGING: 0
      # could define the user locally here, but doing it at the repo level for practice
      LAMBDATEST_USER: ${{ vars.LAMBDATEST_USER }}
      # secrets have to be define in the env section before being referenced
      LAMBDATEST_KEY: ${{ secrets.LAMBDATEST_KEY }}
      # note that run commmands are performed by the shell and so can use $VARIABLE syntax, but
      # lines that are processed by Github Actions are not and require YAML variable syntax, such as
      # $ {{ env.lambdatest_user == 'jimjones' }}
    defaults:
      run:
        working-directory: learning_js/test-automation-practice
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} # default
          ref: "" # defaults to SHA that triggered the workflow
          fetch-depth: 1 # default
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Build project
        run: pnpm build
      - name: Set up LambdaTest Tunnel and background it
        run: ( ./LambdaTestTunnel-Linux --user $LAMBDATEST_USER --key $LAMBDATEST_KEY & )
      - name: Run Playwright tests via LambdaTest on build project
        # can't fully parallelize tests because the returning results from LambdaTest cause only one browser to succeed
        run: ( pnpm exec playwright test --project=chromium ) &
      - name: Run Playwright tests via LambdaTest on build project - part 2
        run: ( pnpm exec playwright test --project=webkit ) &
      - name: wait till subshells finish
        run: wait
